services:
  - type: web
    name: prescription-ocr-api
    env: python
    region: oregon  # Change to your preferred region
    plan: free  # You can set 'starter' or other plan if needed
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: TRANSFORMERS_CACHE
        value: /var/cache/huggingface  # Optional but recommended for transformer models
